# Generated by Django 4.2.7 on 2023-11-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_data_age"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data", old_name="heights", new_name="height",
        ),
    ]
