# Generated by Django 4.2.7 on 2023-11-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_rename_heights_data_height"),
    ]

    operations = [
        migrations.RemoveField(model_name="data", name="height",),
        migrations.AddField(
            model_name="data",
            name="heights",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
