# Generated by Django 4.2.7 on 2023-11-07 04:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_remove_data_height_data_heights"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data",
            old_name="heights",
            new_name="height",
        ),
    ]
